### ISSUE TITLE
Pass on any gene burden papers to Open targets

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/xgwas-curator-tasks#13]
Open targets are ingesting gene burden analyses, but they don't have any systematic way to identify these. A curator should review the lit search list and identify all the studies from the last 6m-1yr, to pass on to Open Targets. This could be done monthly going forward.

**Comment by ljwh2** [comment]
@earlEBI I realised we said longer than 1 yr in the meeting just now, maybe start with 6m-1 year and see how time consuming it is

**Comment by earlEBI** [comment]
@ljwh2 I've added a gene-based tab to the literature triage Google Sheets doc. 
There's a list of 37 gene-based GWAS publications, searching from April 2022 onwards. 
I cleaned up the 'gwas catalog outcome' column to hopefully make sense to Open Targets. 
Only checked [and removed quite a few of] those with ambiguous triage comments. Otherwise, inclusion is based on triage comment only.

**Comment by earlEBI** [comment]
Just curating a publication which I notice also carried out gene-based analysis (PMID 36699085). I don't think most papers which carry out both SV and gene-based will be noted in the literature triage? Should curators just add them to the sheet as we come across them?

**Comment by ljwh2** [comment]
You're right, they won't and that's a good idea to ask curators to note them in the tab in the literature triage sheet
