### ISSUE TITLE
2 studies with lower case alleles

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/xgwas-curator-tasks#8]
GCST001351
GCST90027161

**Comment by earlEBI** [comment]
For the first one, which has no submission attached, I can't edit the SNP in curation app (told not to), and I can't create a new submission because it is closed. I would need developers' help to reopen this one, I think. Not sure how it's been done in the past / how other curators plan to get around this.

**Comment by ljwh2** [comment]
OK I see the problem, I will follow up with devs

**Comment by earlEBI** [comment]
GCST90027161 is complete. 
(Associations had originally been curated through Curation App. I copied the SNPs over to the submission template and recurated through depocuration app, imported and re-published.)

**Comment by earlEBI** [comment]
Both studies have now been fixed and re-published.
