### ISSUE TITLE
Study with no beta direction

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/xgwas-curator-tasks#9]
https://www.ebi.ac.uk/gwas/studies/GCST000069 has no beta unit or direction.

**Comment by earlEBI** [comment]
@ljwh2 I've added 'increase' in this case but I think there might be more cases like this still in the Catalog, because the unit is % variance, see table: https://www.nature.com/articles/ng2108/tables/1 
and curation notes: http://ves-ebi-e4.ebi.ac.uk:8080/gwas/curation/studies/64/notes
'% variance' was put into the 'OR/beta description' field which isn't shown in the UI but is put into the associations download 95% CI (TEXT)' field: 

![assocs in UI.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/ecfb25ec-5bee-42ad-9d13-8d9061a52c25)

![assocs download.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/0e2cdb64-f20e-4eb5-aac5-8db15e8d4dd7)
The following are other GCSTs which I think are affected in the same way: 
GCST000565
GCST000473
GCST000069
GCST000519
GCST000556

I don't know if this is just specific to associations with '% variance' as unit... or if it's wrong to change to 'increase' but we have to put a direction these days to pass validation.

**Comment by earlEBI** [comment]
All those studies above are from <=2010. Here's an example of a study curated in 2017 with % variance increase: https://www.ebi.ac.uk/gwas/studies/GCST004921 
Two studies from 2009 were re-curated in 2017 and there are curation notes mentioning that % variance had to be moved to beta unit the same as I have done: http://ves-ebi-e4.ebi.ac.uk:8080/gwas/curation/studies/5245/notes

**Comment by earlEBI** [comment]
GCST000069: also had to add CoR in order to republish. Done.

**Comment by ljwh2** [comment]
@eks-ebi to create new ticket for wider problem, check if these GCSTs are included

**Comment by eks-ebi** [comment]
closing this ticket as referenced in new broader ticket
